events {}

http {

    server {

        listen 80;

        # React Frontend
        location / {
            proxy_pass http://frontend:3000;
        }

        # Flask Backend
        location /api/ {
            proxy_pass http://backend:5000/;
        }

    }

}