name: CarsForSale CI

on:
  push:
    branches:
      - main

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: docker build -t cars-backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t cars-frontend ./frontend

          